"""empty message

Revision ID: 03a5681cf163
Revises: 0a554f09bd39
Create Date: 2025-06-30 14:24:47.135927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a5681cf163'
down_revision: Union[str, None] = '0a554f09bd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribes', 'role_permitions',
               existing_type=sa.INTEGER(),
               nullable=1)
    op.alter_column('users', 'steam_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'steam_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('subscribes', 'role_permitions',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
