"""empty message

Revision ID: 0f0c59835fd0
Revises: 0fd60f2e0438
Create Date: 2025-06-23 14:12:40.463747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0c59835fd0'
down_revision: Union[str, None] = '0fd60f2e0438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes', sa.Column('role_permitions', sa.Integer(), nullable=1))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('subscribes', 'role_permitions')
    # ### end Alembic commands ###
