"""empty message

Revision ID: 427840400a33
Revises: 0f0c59835fd0
Create Date: 2025-06-23 15:46:08.031507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427840400a33'
down_revision: Union[str, None] = '0f0c59835fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribes', 'role_permitions',
               existing_type=sa.INTEGER(),
               nullable=1)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribes', 'role_permitions',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
