"""empty message

Revision ID: 72e4db5dbd29
Revises: 750f563c5543
Create Date: 2025-07-08 14:25:31.985697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e4db5dbd29'
down_revision: Union[str, None] = '750f563c5543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribes', 'role_permitions',
               existing_type=sa.INTEGER(),
               nullable=1)
    op.drop_constraint(op.f('users_to_whishlist_user_id_fkey'), 'users_to_whishlist', type_='foreignkey')
    op.create_foreign_key(None, 'users_to_whishlist', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_to_whishlist', type_='foreignkey')
    op.create_foreign_key(op.f('users_to_whishlist_user_id_fkey'), 'users_to_whishlist', 'users', ['user_id'], ['id'])
    op.alter_column('subscribes', 'role_permitions',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
