"""empty message

Revision ID: 750f563c5543
Revises: 3162bc6335bf
Create Date: 2025-07-08 14:21:36.739684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750f563c5543'
down_revision: Union[str, None] = '3162bc6335bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribes', 'role_permitions',
               existing_type=sa.INTEGER(),
               nullable=1)
    op.drop_constraint(op.f('subscribes_user_id_fkey'), 'subscribes', type_='foreignkey')
    op.create_foreign_key(None, 'subscribes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribes', type_='foreignkey')
    op.create_foreign_key(op.f('subscribes_user_id_fkey'), 'subscribes', 'users', ['user_id'], ['id'])
    op.alter_column('subscribes', 'role_permitions',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
